name: Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lib

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up python 3.12.7
        uses: actions/setup-python@v3
        with:
          python-version: '3.12.7'

      - name: Install binary uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Sync dependencies
        run: uv sync

      - name: Run pytests
        run: uv run pytest -v
